name: Cron Job For Publish To Github Pages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: npm run start:crawler
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Hourly cron job for logs update
